#include <assert.h>

typedef unsigned int GLuint;

#define GL_TRUE 1
#define GL_FALSE 0

#define GL_LINEAR __LINE__
#define GL_CLAMP_TO_EDGE __LINE__
#define GL_VENDOR __LINE__
#define GL_RENDERER __LINE__
#define GL_VERSION __LINE__
#define GL_EXTENSIONS __LINE__
#define GL_COLOR_BUFFER_BIT __LINE__
#define GL_NEAREST __LINE__
#define GL_TEXTURE_2D __LINE__
#define GL_LINES __LINE__
#define GL_RGB __LINE__
#define GL_RGBA __LINE__
#define GL_ALPHA __LINE__
#define GL_KEEP __LINE__
#define GL_REPLACE __LINE__
#define GL_ALWAYS __LINE__
#define GL_BACK __LINE__
#define GL_UNSIGNED_BYTE __LINE__
#define GL_ONE __LINE__
#define GL_ZERO __LINE__
#define GL_SRC_ALPHA __LINE__
#define GL_NOTEQUAL __LINE__
#define GL_TEXTURE1_ARB __LINE__
#define GL_TEXTURE0_ARB __LINE__
#define GL_ONE_MINUS_SRC_ALPHA __LINE__
#define GL_GREATER __LINE__
#define GL_PROJECTION __LINE__
#define GL_TEXTURE __LINE__
#define GL_MODELVIEW __LINE__
#define GL_CLAMP __LINE__
#define GL_TEXTURE_WRAP_S __LINE__
#define GL_TEXTURE_WRAP_T __LINE__
#define GL_TEXTURE_MAG_FILTER __LINE__
#define GL_TEXTURE_MIN_FILTER __LINE__

#define glGetString(...) NULL
#define glClearColor(...) assert(0)
#define glClear(...) assert(0)
#define glEnable(...) assert(0)
#define glDisable(...) assert(0)
#define glBegin(...) assert(0)
#define glColor4f(...) assert(0)
#define glColorMask(...) assert(0)
#define glStencilMask(...) assert(0)
#define glClearStencil(...) assert(0)
#define glColor3fv(...) assert(0)
#define glVertex3f(...) assert(0)
#define glEnd(...) assert(0)
#define glBindTexture(...) assert(0)
#define glTexCoord2f(...) assert(0)
#define glViewport(...) assert(0)
#define glCopyTexImage2D(...) assert(0)
#define glStencilOp(...) assert(0)
#define glStencilFunc(...) assert(0)
#define glVertex3fv(...) assert(0)
#define glColor3f(...) assert(0)
#define glReadBuffer(...) assert(0)
#define glReadPixels(...) assert(0)
#define glBlendFunc(...) assert(0)
#define glActiveTextureARB(...) assert(0)
#define glMultiTexCoord2fARB(...) assert(0)
#define glColor4fv(...) assert(0)
#define glTexCoord2fv(...) assert(0)
#define glAlphaFunc(...) assert(0)
#define glMatrixMode(...) assert(0)
#define glLoadIdentity(...) assert(0)
#define glFrustum(...) assert(0)
#define glOrtho(...) assert(0)
#define glMultMatrixf(...) assert(0)
#define glTranslatef(...) assert(0)
#define glTexParameteri(...) assert(0)
#define glTexImage2D(...) assert(0)
#define glGenTextures(...) assert(0)
#define glDepthMask(...) assert(0)
